server:
  port: 0
spring:
  cloud:
    stream:
      function:
        bindings:
          nameSink-in-0: sinkinput
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: demandData
      port: 27017
      host: localhost