server:
  port: 8080

spring:
  application:
    name: ieso-bff
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: demandData
      port: 27017
      host: localhost
